<?php
// includes/email-config.php - Email configuration
// Auto-generated on 2025-09-10 16:55:45

return array (
  'settings' => 
  array (
    'enabled' => true,
    'test_mode' => false,
    'fallback_to_php_mail' => true,
  ),
  'sendinblue' => 
  array (
    'api_key' => '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',
    'from_email' => 'info@bluefifth.in',
    'from_name' => 'Bluefifith Team',
  ),
  'smtp' => 
  array (
    'host' => '',
    'port' => 0,
    'username' => '',
    'password' => '',
    'encryption' => 
    array (
      0 => 'tls',
      1 => 'tls',
      2 => 'tls',
      3 => 'tls',
      4 => 'tls',
      5 => 'tls',
      6 => 'tls',
      7 => 'tls',
      8 => 'tls',
      9 => 'tls',
      10 => 'tls',
      11 => 'tls',
      12 => 'tls',
      13 => 'tls',
      14 => 'tls',
      15 => 'tls',
      16 => 'tls',
      17 => 'tls',
      18 => 'tls',
      19 => 'tls',
      20 => 'tls',
      21 => 'tls',
      22 => 'tls',
      23 => 'tls',
      24 => 'tls',
      25 => 'tls',
      26 => 'tls',
      27 => 'tls',
      28 => 'tls',
      29 => 'tls',
      30 => 'tls',
      31 => 'tls',
      32 => 'tls',
      33 => 'tls',
      34 => 'tls',
      35 => 'tls',
      36 => 'tls',
      37 => 'tls',
      38 => 'tls',
      39 => 'tls',
      40 => 'tls',
      41 => 'tls',
      42 => 'tls',
      43 => 'tls',
      44 => 'tls',
      45 => 'tls',
      46 => 'tls',
      47 => 'tls',
      48 => 'tls',
      49 => 'tls',
      50 => 'tls',
      51 => 'tls',
      52 => 'tls',
      53 => 'tls',
      54 => 'tls',
      55 => 'tls',
      56 => 'tls',
      57 => 'tls',
      58 => 'tls',
      59 => 'tls',
      60 => 'tls',
      61 => 'tls',
      62 => 'tls',
      63 => 'tls',
      64 => 'tls',
      65 => 'tls',
      66 => 'tls',
      67 => 'tls',
      68 => 'tls',
      69 => 'tls',
      70 => 'tls',
      71 => 'tls',
      72 => 'tls',
      73 => 'tls',
      74 => 'tls',
      75 => 'tls',
      76 => 'tls',
      77 => 'tls',
      78 => 'tls',
      79 => 'tls',
      80 => 'tls',
      81 => 'tls',
      82 => 'tls',
      83 => 'tls',
      84 => 'tls',
    ),
  ),
);
?>